config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :contact
  resources :posts

  get 'sitemap.xml',  to: 'home#sitemap',  defaults: { format: :xml },   as: :sitemap
  get 'robots.txt',   to: 'home#robots',   defaults: { format: :text },  as: :robots

  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessor :remove_image

  IMAGE_MEDIUM_SIZE = "922x434"
  IMAGE_THUMB_SIZE = "340x160"

  is_impressionable
  has_attached_file :image, styles: { medium: "#{IMAGE_MEDIUM_SIZE}>", thumb: "#{IMAGE_THUMB_SIZE}>" }, default_url: "blog/:style/missing.png"

  before_validation { self.image.clear if remove_image? }

  validates :title, :description, :content, presence: true
  validates :title, uniqueness: true
  validates :title, length: { in: 3..150 }
  validates :description, length: { in: 3..200 }
  validates :content, length: { in: 3..60000 }
  validates :published, inclusion: { in: [true, false] }
  validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png"]
  validates_attachment_size :image, :less_than => 1.megabyte

  scope :published, -> { where(published: true) }

  def unique_views
    impressionist_count(filter: :ip_address)
  end

  def remove_image?
    remove_image == "1"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def create
    @contact_email = ContactMailer.contact_email(contact_params)

    respond_to do |format|
      format.json do
        if @contact_email.deliver
          render json: { message: "Thank you #{contact_params[:name]}! Your email is forwarded and Nino will get back to you during his next coffee break." } 
        else
          render json: { message: "Something went wrong!" } 
        end
      end
    end
  end

  private

    def contact_params
      params.permit(:name, :email, :subject, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.published
  end

  def sitemap
    path = Rails.root.join('public', 'sitemaps', 'sitemap.xml')
    if File.exists?(path)
      render xml: open(path).read
    else
      render text: 'Sitemap not found.', status: :not_found
    end
  end

  def robots
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.published.find(params[:id])
    impressionist(@post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title="")
    base_title = "Nino - Ruby on Rails Engineer"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end

  def markdown(text)
    MARKDOWN.render(text).html_safe
  end

  def format_date(date)
    date.strftime("%d %b %Y")
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_position(path)
    "#{path}#title"
  end

  def available_posts?
    Post.published.any?
  end
end

app/views/home/index.html.erb
<%= render 'shared/info' %>

<%= render 'shared/profile' %>

<%= render 'shared/education' %>

<%= render 'shared/experience' %>

<%= render 'shared/skills' %>

<%= render 'shared/clients' %>

<%= render 'shared/blog' if available_posts? %>

<%= render 'shared/contact' %>

app/views/home/robots.text.erb
Sitemap: <%= sitemap_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <meta name="title" content="Nino - Ruby on Rails Engineer">
    <meta name="keywords" content="Ruby, Rails, Engineer, Consultant, Developer, Programmer, Remote, Part-Time, Full-Time, Nino, Ninoslav, Milenovic, Milenović">
    <meta name="description" content="Software engineer and technical lead. Open-source enthusiast and mentor at Rails Girls Serbia. Passionate about start-ups and a technical leader that can help build the next hot venture in a Ruby environment from the ground up.">
    <meta name="robots" content="all">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,700,800,400,600' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= disqus_init %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-57005641-1', 'auto');
      ga('require', 'displayfeatures');
      ga('require', 'linkid', 'linkid.js');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    <div id="preloader">
      <div id="status">&nbsp;</div>
      <noscript>JavaScript is off. Please enable to view full site.</noscript>
    </div>

    <div class="wrapper">
      <div class="container">
        <%= render 'shared/header' %>

        <%= yield %>

        <%= render 'shared/footer' %>
      </div>
    </div>

    <a class="goto-top" href="#gotop"></a>
  </body>
</html>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<section class="single-post big-name">
  <div class="sticky-paper-head has-shadow">
    <div class="content">
      <h1>Nino</h1>
      <div class="short-tag">
        ruby on rails engineer
      </div>
    </div>
  <div class="shadow"></div></div>

  <a name="title"></a>

  <div class="sticky-paper-body has-shadow">
    <div class="content">
      <div class="short-desc">
        <%= @post.title %>
      </div>

      <div class="single-post">
        <div class="date">
          <%= format_date(@post.created_at) %>
        </div>

        <div class="content">
          <%= markdown(@post.content) %>
        </div>

        <div class="share-row">
          <div class="row">
            <div class="col-xs-12 col-sm-10">
              <ul class="social-icons small">
                <li><strong>Share on</strong></li>
                
                <li><a class="fa fa-linkedin" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=<%= post_position(post_url(@post)) %>&amp;title=<%= @post.title %>&amp;source=<%= root_url %>"></a></li>
                <li><a class="fa fa-twitter" href="http://twitter.com/home?status=<%= @post.title %>+<%= post_position(post_url(@post)) %>"></a></li>
                <li><a class="fa fa-facebook" href="http://www.facebook.com/share.php?u=<%= post_position(post_url(@post)) %>&amp;title=<%= @post.title %>"></a></li>
              </ul> 
            </div>
            <div class="col-xs-12 col-sm-2 counter-holder">
              <div class="counter">
                <span><%= @post.unique_views %></span> views 
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

<hr class="le-hre">

<section>
  <div class="sticky-paper-head has-shadow">
    <div class="content ">
      <h1>comments</h1>
    </div>
  </div>

  <div class="sticky-paper-body has-shadow">
    <div class="content">
      <%- disqus_thread %>
    </div>
  </div>
</section>

app/views/shared/_blog.html.erb
<hr class="le-hre">

<section id="blog" >
  <div class="sticky-paper-head has-shadow">
    <div class="content">
      <h1>Blog</h1>
    </div>
  </div>

  <div class="sticky-paper-body has-shadow">
    <div class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="blog-list-holder row">
            <% @posts.each do |post| %>
              <div class="blog-item item col-xs-12 col-md-6 col-lg-4">
                
                <div class="thumb has-shadow">
                  <div class="date">
                    <%= format_date(post.created_at) %>
                  </div> 
                  <%= link_to(image_tag(post.image.url(:medium), width: 340), post_position(post_path(post))) %>
                </div>
                <div class="info-area">

                  <div class="title">
                    <%= post.title %>
                  </div>
                  <div class="excerpt">
                    <p>
                      <%= post.description %>
                    </p>
                  </div>

                  <%= link_to 'Read more', post_position(post_path(post)), class: 'le-btn' %>
                </div>

              </div>
            <% end unless @posts.empty? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_clients.html.erb
<hr class="le-hre">

<section id="clients">
  <div class="sticky-paper-head has-shadow">
    <div class="content">
      <h1>clients</h1>
    </div>
  </div>

  <div class="sticky-paper-body has-shadow">
    <div class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="portfolio-holder">
            <div id="portfolio-grid" class="row">

              <figure class="col-xs-12 col-sm-6 col-md-4 portfolio-item marketing">
                <a><%= image_tag('portfolio/work09.jpg', alt: 'Conichi', width: 350) %></a>
                <div class="holder">
                  <div class="paper has-shadow title">
                    <div class="content">
                      Conichi
                    </div>
                  </div>

                  <div class="paper has-shadow category">
                    <div class="content">
                      smart hotels platform
                    </div>
                  </div>
                </div>
              </figure>

              <figure class="col-xs-12 col-sm-6 col-md-4 portfolio-item marketing">
                <a><%= image_tag('portfolio/work01.jpg', alt: 'Aquipa Partner', width: 350) %></a>
                <div class="holder">
                  <div class="paper has-shadow title">
                    <div class="content">
                      Aquipa Partner
                    </div>
                  </div>

                  <div class="paper has-shadow category">
                    <div class="content">
                      customer acquisition platform
                    </div>
                  </div>
                </div>
              </figure>

              <figure class="col-xs-12 col-sm-6 col-md-4 portfolio-item marketing entertainment">
                <a><%= image_tag('portfolio/work06.jpg', alt: 'NBC Universal', width: 350) %></a>
                <div class="holder">
                  <div class="paper has-shadow title">
                    <div class="content">
                      nbc universal
                    </div>
                  </div>

                  <div class="paper has-shadow category">
                    <div class="content">
                      media and entertainment
                    </div>
                  </div>
                </div>
              </figure>

              <figure class="col-xs-12 col-sm-6 col-md-4 portfolio-item streaming entertainment">
                <a><%= image_tag('portfolio/work05.jpg', alt: 'Hulu', width: 350) %></a>
                <div class="holder">
                  <div class="paper has-shadow title">
                    <div class="content">
                      hulu
                    </div>
                  </div>

                  <div class="paper has-shadow category">
                    <div class="content">
                      video streaming service
                    </div>
                  </div>
                </div>
              </figure>

              <figure class="col-xs-12 col-sm-6 col-md-4 portfolio-item entertainment">
                <a><%= image_tag('portfolio/work04.jpg', alt: 'Astrology', width: 350) %></a>
                <div class="holder">
                  <div class="paper has-shadow title">
                    <div class="content">
                      astrology
                    </div>
                  </div>

                  <div class="paper has-shadow category">
                    <div class="content">
                      live astrology services
                    </div>
                  </div>
                </div>
              </figure>

              <figure class="col-xs-12 col-sm-6 col-md-4 portfolio-item entertainment">
                <a><%= image_tag('portfolio/work11.jpg', alt: 'iVillage', width: 350) %></a>
                <div class="holder">
                  <div class="paper has-shadow title">
                    <div class="content">
                      ivillage
                    </div>
                  </div>

                  <div class="paper has-shadow category">
                    <div class="content">
                      media and entertainment
                    </div>
                  </div>
                </div>
              </figure>

              <figure class="col-xs-12 col-sm-6 col-md-4 portfolio-item entertainment">
                <a><%= image_tag('portfolio/work08.jpg', alt: 'Exit Reality', width: 350) %></a>
                <div class="holder">
                  <div class="paper has-shadow title">
                    <div class="content">
                      Exit Reality
                    </div>
                  </div>

                  <div class="paper has-shadow category">
                    <div class="content">
                      virtual reality pioneer
                    </div>
                  </div>
                </div>
              </figure>

              <figure class="col-xs-12 col-sm-6 col-md-4 portfolio-item entertainment">
                <a><%= image_tag('portfolio/work12.jpg', alt: 'Macmillan Digital Education', width: 350) %></a>
                <div class="holder">
                  <div class="paper has-shadow title">
                    <div class="content">
                      Digital Education
                    </div>
                  </div>

                  <div class="paper has-shadow category">
                    <div class="content">
                      leading educational publisher
                    </div>
                  </div>
                </div>
              </figure>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_contact.html.erb
<hr class="le-hre">

<section id="contact">
  <div class="sticky-paper-head has-shadow">
    <div class="content">
      <h1>contact</h1>
    </div>
  </div>

  <div class="sticky-paper-body has-shadow">
    <div class="content">
      <div class="row row-contact">

        <div class="col-xs-12 col-md-8"> 
          <div class="contact-form-holder">
            <div class="message-box"></div>
            <%= form_tag(contact_index_path, class: 'contact-form', id: 'contact-form', remote: true, authenticity_token: true) do %>
              <div class="col-xs-12 col-sm-6 no-margin">
                <div class="control-group">
                  <div class="controls">
                    <input id="cname" data-placeholder="Your Name*" name="name" size="25" class="le-input required col-xs-12" />
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-sm-6 no-margin">
                <div class="control-group">
                  <div class="controls">
                    <input id="cemail" data-placeholder="Your Email*" name="email" class="le-input required email col-xs-12" />
                  </div>
                </div>
              </div>

              <div class="col-xs-12  no-margin">
                <div class="control-group">
                  <div class="controls">
                    <input id="subject" data-placeholder="Subject" name="subject" size="25" class="le-input col-xs-12" />
                  </div>
                </div>
              </div>

              <div class="col-xs-12 no-margin">
                <div class="control-group">
                  <div class="controls">
                    <textarea id="ccomment" class="le-input col-xs-12 no-margin" name="message" rows="9" cols="5" data-placeholder="Message" ></textarea>
                  </div>
                </div>
              </div>

              <div class="col-xs-12 no-margin">
                <div class="button-holder">
                  <input class="submit le-btn big" type="submit" value="Send" />
                </div>
                <div id="loading" class="pull-right">
                  <%= image_tag('loader.gif', alt: 'Loading...') %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="col-xs-12 col-md-4"> 
          <div class="contact-info">

            <div class="social-icons">
              <ul>
                <li>
                  <a class="fa fa-linkedin" href="https://www.linkedin.com/in/ninoslavmilenovic"></a>
                </li>
                <li>
                  <a class="fa fa-github" href="https://github.com/rubyengineer"></a>
                </li>
                <li>
                  <a class="fa fa-twitter" href="https://twitter.com/ruby_engineer"></a>
                </li>
                <li>
                  <a class="fa fa-google-plus" href="https://google.com/+NinoslavMilenović"></a>
                </li>
                <li>
                  <a class="fa fa-youtube" href="https://www.youtube.com/user/ninosempire"></a>
                </li>
              </ul>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/shared/_education.html.erb
<hr class="le-hre">

<section id="education">
  <div class="sticky-paper-head has-shadow">
    <div class="content">
      <h1>education</h1>
    </div>
  </div>

  <div class="sticky-paper-body has-shadow">
    <div class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="timeline-holder wow bounceInUp"> 
            <div class="timeline-head event-head">
              <div class="icon">
                <i class="fa fa-university"></i>
              </div>
            </div>

            <div class="timeline-body">
              <div class="event-item timeline-item">
                <div class="event-title left">
                  <h1>information technology</h1>
                  <h4>undergraduate degree</h4>
                </div>

                <div class="event-content timeline-content right">
                  <p>
                    Focused on principles of software engineering, advanced algorithms and in depth database design. Received an introduction to basic theory and applied mathematics. Acquired strong critical thinking skills.
                  </p>
                </div>
              </div>

              <div class="event-item timeline-item">
                <div class="event-title right">
                  <h1>communications technology</h1>
                  <h4>postgraduate degree</h4>
                </div>

                <div class="event-content timeline-content left">
                  <p>
                    Focused on expanding skills in creating, planning and developing communication systems for businesses. Acquired knowledge to integrate the latest technology in web, multimedia and telecommunication systems, and performed research in the field.
                  </p>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_experience.html.erb
<hr class="le-hre">

<section id="experience">
  <div class="sticky-paper-head has-shadow">
    <div class="content">
      <h1>experience</h1>
    </div>
  </div>

  <div class="sticky-paper-body has-shadow">
    <div class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="timeline-holder wow bounceInUp">
            <div class="timeline-head event-head">
              <div class="icon">
                <i class="fa fa-suitcase"></i>
              </div>
            </div>
            <div class="timeline-body">
              <div class="event-item timeline-item">
                <div class="event-title right">
                  <h1>founder</h1>
                  <h4>47international <small>2015-present</small></h4>
                </div>

                <div class="event-content timeline-content left">
                  <p>
                    A digital creative agency partnering with distributed teams of world class consultants spread across the globe. The remote nature of our teams ensures our presence on both western and eastern markets which proved to be an extremely successful model for many startups as well as large established businesses. 
                    We focus on web solutions and feature rapid prototyping and software development, mainly by using Ruby on Rails framework.
                  </p>
                </div>
              </div>
              <div class="event-item timeline-item">
                <div class="event-title left">
                  <h1>backend lead</h1>
                  <h4>conichi <small>2015-present</small></h4>
                </div>

                <div class="event-content timeline-content right">
                  <p>
                    Utilizing <strong>beacon technology</strong>, Conichi developed a software solution that lets you skip the hotel check-in/check-out process, enables you to pay for all the services using your smartphone and enhances every stage of your stay, seamlessly taking care of your little travel hurdles. Nino is in charge of all the backend development and deployment processes.
                  </p>
                </div>
              </div>
              <div class="event-item timeline-item">
                <div class="event-title right">
                  <h1>technical lead</h1>
                  <h4>aquipa partner <small>2013-2015</small></h4>
                </div>

                <div class="event-content timeline-content left">
                  <p>
                    Establishing and supervising the software development process, setting short-term objectives, assessing progress, conducting code reviews, establishing an application deployment process, monitoring application performance and working with founders to develop and refine user stories and translate them into compelling products and features.
                  </p>
                </div>
              </div>

              <div class="event-item timeline-item">
                <div class="event-title left">
                  <h1>mentor</h1>
                  <h4>rails girls <small>2013-present</small></h4>
                </div>

                <div class="event-content timeline-content right">
                  <p>
                    Rails Girls is <strong>volunteer-run non-profit community</strong> dedicated to giving women the tools to create awesome web applications.
                    Committed to help learners of all skill levels, from beginners tackling early challenges to experienced developers who need help on specific problems.
                  </p>
                </div>
              </div>

              <div class="event-item timeline-item">
                <div class="event-title right">
                  <h1>ruby on rails engineer</h1>
                  <h4>international consultant <small>2011-present</small></h4>
                </div>

                <div class="event-content timeline-content left">
                  <p>
                    Writing well architected, tested, maintainable code, performing dev-ops and server wrangling on cloud-scale infrastructures, deploying amazing web applications with Ruby on Rails and collaborating with some of the biggest names in the industry.
                  </p>
                </div>
              </div>

              <div class="event-item timeline-item">
                <div class="event-title left">
                  <h1>ruby engineer</h1>
                  <h4>nbcuniversal, inc <small>2011-2013</small></h4>
                </div>

                <div class="event-content timeline-content right">
                  <p>
                    Contributed in building the web infrastructure for one of the world’s leading media and entertainment companies in the development, production and marketing of entertainment, news and information to a global audience. 
                  </p>
                </div>
              </div>

              <div class="event-item timeline-item">
                <div class="event-title right">
                  <h1>ruby developer</h1>
                  <h4>kolosek <small>2011-2013</small></h4>
                </div>

                <div class="event-content timeline-content left">
                  <p>
                    Worked on multiple projects and had roles ranging from design, development, test and deployment to <strong>critical optimizations</strong> and integrations with third-party services.
                  </p>
                </div>
              </div>

              <div class="event-item timeline-item">
                <div class="event-title left">
                  <h1>python developer</h1>
                  <h4>tonet <small>2009-2011</small></h4>
                </div>

                <div class="event-content timeline-content right">
                  <p>
                    Designed, developed and deployed a Management Information System based on Data Warehouse as part of Infrastructural Information System for natural gas distribution along with other internal tools such as Mass Bill Printing software, SMS gateway and BI reports generator.
                  </p>
                </div>
              </div>

              <div class="event-item timeline-item">
                <div class="event-title right">
                  <h1>python developer</h1>
                  <h4>freelancer <small>2008-2009</small></h4>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<section id="footer">
  <div class="sticky-paper-head has-shadow">
    <div class="content">
      <div class="copyright">Copyright © <%= Time.now.year %> ● rubyengineer.com</div>
    </div>
  </div>
</section>

app/views/shared/_header.html.erb
<header id="home">
  <div class="head-image bg-image" data-bg-image="<%= image_path('head-image.jpg') %>">
    <div class="avatar wow bounceInDown" >
        <%= image_tag('avatar.jpg') %>
    </div>
  </div>

  <div class="sticky-paper-head has-shadow">
    <div class="content">
      <div class="social-icons">
        <ul>
          <li>
            <a class="fa fa-linkedin" href="https://www.linkedin.com/in/ninoslavmilenovic"></a>
          </li>
          <li>
            <a class="fa fa-github" href="https://github.com/rubyengineer"></a>
          </li>
          <li>
            <a class="fa fa-twitter" href="https://twitter.com/ruby_engineer"></a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xs-12 nav-menu top-menu-holder">
    <nav class="hidden-xs visible-lg ">
      <ul class="nav">
        <li class="active">
          <a href="#home">home</a>
        </li>
        <li>
          <a href="#profile">profile</a>
        </li>
        <li>
          <a href="#education">education</a>
        </li>
        <li>
          <a href="#experience">experience</a>
        </li>
        <li>
          <a href="#skills">skills</a>
        </li>
        <li>
          <a href="#clients">clients</a>
        </li>
        <% if available_posts? %>
          <li>
            <a href="#blog">blog</a>
          </li>
        <% end %>
        <li>
          <a href="#contact">contact</a>
        </li>
      </ul>
    </nav>

    <select class="top-drop-menu nav visible-md visible-sm visible-xs hidden-lg">
      <option value="#home" selected="selected">
        Home
      </option>

      <option value="#profile">
        Profile
      </option>

      <option value="#education">
        Education
      </option>

      <option value="#experience">
        Experience
      </option>

      <option value="#skills">
        Skills
      </option>

      <option value="#clients">
        Clients
      </option>

      <% if available_posts? %>
        <option value="#blog">
          Blog
        </option>
      <% end %>

      <option value="#contact">
        Contact
      </option>
    </select>
  </div>
</header>